### ISSUE TITLE
Out of memory with 512 x 512 x 144 images

### ISSUE THREAD

**Issue by arthursw** [MedICL-VU/LesionSeg#4]
Hi,

I have the following error while trying to run the training with a `trainSize` of 512:

`RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 23.90 GiB total capacity; 23.13 GiB already allocated; 106.38
MiB free; 31.58 MiB cached)`

Here is the command I run:
`python3 train.py --loss_to_use focal --input_nc 3 --trainSize 512 --test_mode val --name fir
st_test --eval_val`

And here is the full log:

```
Setting up a new session...
INFO:tornado.access:200 POST /env/main (127.0.0.1) 0.91ms
INFO:tornado.access:101 GET /vis_socket (127.0.0.1) 0.89ms
INFO:root:Opened visdom socket from ip: 127.0.0.1
create web directory ../Checkpoints/first_test/web...
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    model.optimize_parameters()
  File "/home/amasson/LesionSeg/models/ms_model.py", line 85, in optimize_parameters
    self.forward()
  File "/home/amasson/LesionSeg/models/ms_model.py", line 65, in forward
    self.fake_mask = self.netG(torch.cat([getattr(self, k) for k in MODALITIES], 1))
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amasson/LesionSeg/models/tiramisu_model.py", line 93, in forward
    out = self.denseBlocksUp[i](out)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amasson/LesionSeg/models/tiramisu_layers.py", line 32, in forward
    out = layer(x)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amasson/LesionSeg/models/tiramisu_layers.py", line 15, in forward
    return super().forward(x)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/amasson/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1656, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 23.90 GiB total capacity; 23.13 GiB already allocated; 106.38
MiB free; 31.58 MiB cached)

```

What can I do? Should I downsize my images?

**Comment by HuahongZhang** [comment]
Hi, sorry for the late reply, I didn't receive any notification from GitHub.

I think this looks like a real out-of-memory instead of a bug. So to fix this, I would simply choose to use a batchsize = 256 or 128 for training. You don't need to downsize your images unless you want to catch more global information.

**Comment by arthursw** [comment]
Thanks a lot, I'll try that (although I'll be working on another project for some weeks)!
