### ISSUE TITLE
RuntimeError: Couldn't open shared event

### ISSUE THREAD

**Issue by Kristin-cantonese** [MedICL-VU/LesionSeg#7]
My code always end up with this error during training. Could you please tell me how to solve it?

**Comment by HuahongZhang** [comment]
Hi, I am not sure this error is the same but I used to get "RuntimeError: unable to open shared memory object". I didn't find the reason but it can be simply solved if I use Pycharm to run the code.

**Comment by Kristin-cantonese** [comment]
Do you mean to use the terminal in Pycharm to run the code? I encounter this problem when running the code in Pycharm.

**Comment by Kristin-cantonese** [comment]
> Hi, I am not sure this error is the same but I used to get "RuntimeError: unable to open shared memory object". I didn't find the reason but it can be simply solved if I use Pycharm to run the code.

Do you mean to use the terminal in Pycharm to run the code? I encounter this problem when running the code in Pycharm.

**Comment by HuahongZhang** [comment]
I got this error when I try to use command line to run the code, but it is OK if I run it with normal PyCharm runs. Can you give more error information here?

**Comment by Kristin-cantonese** [comment]
> I got this error when I try to use command line to run the code, but it is OK if I run it with normal PyCharm runs. Can you give more error information here?

The code terminated at ''model.train()" in train.py in the third cross-valiation during training.

**Comment by HuahongZhang** [comment]
So the first two folds are trained successfully? If yes, an approach (not so elegant) is that you can manually change the fold which you want to train. For example, you can change val_indices to be [5] to train only the fifth fold.

**Comment by Kristin-cantonese** [comment]
> So the first two folds are trained successfully? If yes, an approach (not so elegant) is that you can manually change the fold which you want to train. For example, you can change val_indices to be [5] to train only the fifth fold.

So the number of folds for training do not affect the accuracy? What is your running platform, the version of pytorch and so on.
How to set the parameter 'num_threads' in base_options.py? Should it be less than the number of CPU? Someone online said  'num_threads' may cause this issue.

**Comment by HuahongZhang** [comment]
It should affect the model performance and I usually use 5-fold training. But you can train the different folds separately since they don't interact with each other. I use both Ubuntu 16.04 and 18.04. The pytorch version was around 1.1.0. 
For the num_threads, I think you can set it to 1 or 0? But I remember it didn't help with the error I encountered.

**Comment by Kristin-cantonese** [comment]
> It should affect the model performance and I usually use 5-fold training. But you can train the different folds separately since they don't interact with each other. I use both Ubuntu 16.04 and 18.04. The pytorch version was around 1.1.0.
> For the num_threads, I think you can set it to 1 or 0? But I remember it didn't help with the error I encountered.

Ok, thanks for your help

**Comment by Kristin-cantonese** [comment]
> It should affect the model performance and I usually use 5-fold training. But you can train the different folds separately since they don't interact with each other. I use both Ubuntu 16.04 and 18.04. The pytorch version was around 1.1.0.
> For the num_threads, I think you can set it to 1 or 0? But I remember it didn't help with the error I encountered.

Could you please release the 5-fold validation accuracy during training? We cannot achieve the performance as you shown.

**Comment by HuahongZhang** [comment]
Sure, using the ISBI 2015 challenge data, a sample validation Dice would be [0.776, 0.879, 0.817, 0.719, 0.703]. For example, 0.776 is the average of Dice over the two manual segmentations from subject 1.

**Comment by Kristin-cantonese** [comment]
> Sure, using the ISBI 2015 challenge data, a sample validation Dice would be [0.776, 0.879, 0.817, 0.719, 0.703]. For example, 0.776 is the average of Dice over the two manual segmentations from subject 1.

sorry, We have a question. When the volume size is like 128*256*30, do you have any idea about how to process it in your code?

**Comment by HuahongZhang** [comment]
As I think, the first solution would be set the training sample size to be 30 or 256, so that the code will crop the image to be 3*30*30 or pad the image to be 3*256*256. I assume the padding one will have better result. Another solution is using resizing in both training and testing, but you may need to change the code by yourself, I think cv2.resize will work.

**Comment by y78h11b09** [comment]
Hi,did you solve it?, i got the same error during training
2020-06-09 13:50:06,087 - mmdet - INFO - workflow: [('train', 1)], max: 20 epochs
2020-06-09 13:56:22,778 - mmdet - INFO - Epoch [5][300/8856]	lr: 0.00010, eta: 2 days, 1:18:43, time: 1.256, data_time: 0.092, memory: 4018, train_loss: 1.5078, loss: 1.5078
2020-06-09 14:02:24,076 - mmdet - INFO - Epoch [5][600/8856]	lr: 0.00010, eta: 2 days, 0:12:16, time: 1.204, data_time: 0.037, memory: 4018, train_loss: 1.4931, loss: 1.4931
2020-06-09 14:08:27,846 - mmdet - INFO - Epoch [5][900/8856]	lr: 0.00010, eta: 1 day, 23:52:32, time: 1.213, data_time: 0.037, memory: 4018, train_loss: 1.4962, loss: 1.4962
2020-06-09 14:14:34,010 - mmdet - INFO - Epoch [5][1200/8856]	lr: 0.00010, eta: 1 day, 23:44:19, time: 1.221, data_time: 0.038, memory: 4018, train_loss: 1.4673, loss: 1.4673
2020-06-09 14:20:42,269 - mmdet - INFO - Epoch [5][1500/8856]	lr: 0.00010, eta: 1 day, 23:40:12, time: 1.228, data_time: 0.038, memory: 4018, train_loss: 1.5070, loss: 1.5070
2020-06-09 14:26:49,468 - mmdet - INFO - Epoch [5][1800/8856]	lr: 0.00010, eta: 1 day, 23:34:03, time: 1.224, data_time: 0.039, memory: 4018, train_loss: 1.5125, loss: 1.5125
2020-06-09 14:33:01,129 - mmdet - INFO - Epoch [5][2100/8856]	lr: 0.00010, eta: 1 day, 23:32:50, time: 1.239, data_time: 0.039, memory: 4018, train_loss: 1.4812, loss: 1.4812
2020-06-09 14:39:12,045 - mmdet - INFO - Epoch [5][2400/8856]	lr: 0.00010, eta: 1 day, 23:29:40, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5110, loss: 1.5110
2020-06-09 14:45:22,810 - mmdet - INFO - Epoch [5][2700/8856]	lr: 0.00010, eta: 1 day, 23:25:42, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5186, loss: 1.5186
2020-06-09 14:51:34,151 - mmdet - INFO - Epoch [5][3000/8856]	lr: 0.00010, eta: 1 day, 23:21:43, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.4890, loss: 1.4890
2020-06-09 14:57:46,231 - mmdet - INFO - Epoch [5][3300/8856]	lr: 0.00010, eta: 1 day, 23:17:52, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4969, loss: 1.4969
2020-06-09 15:03:58,149 - mmdet - INFO - Epoch [5][3600/8856]	lr: 0.00010, eta: 1 day, 23:13:31, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4965, loss: 1.4965
2020-06-09 15:10:10,007 - mmdet - INFO - Epoch [5][3900/8856]	lr: 0.00010, eta: 1 day, 23:08:51, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4974, loss: 1.4974
2020-06-09 15:16:21,421 - mmdet - INFO - Epoch [5][4200/8856]	lr: 0.00010, eta: 1 day, 23:03:43, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.5027, loss: 1.5027
2020-06-09 15:22:32,469 - mmdet - INFO - Epoch [5][4500/8856]	lr: 0.00010, eta: 1 day, 22:58:16, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.5043, loss: 1.5043
2020-06-09 15:28:43,404 - mmdet - INFO - Epoch [5][4800/8856]	lr: 0.00010, eta: 1 day, 22:52:39, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.4917, loss: 1.4917
2020-06-09 15:34:55,108 - mmdet - INFO - Epoch [5][5100/8856]	lr: 0.00010, eta: 1 day, 22:47:20, time: 1.239, data_time: 0.039, memory: 4018, train_loss: 1.4882, loss: 1.4882
2020-06-09 15:41:05,177 - mmdet - INFO - Epoch [5][5400/8856]	lr: 0.00010, eta: 1 day, 22:41:13, time: 1.234, data_time: 0.039, memory: 4018, train_loss: 1.5127, loss: 1.5127
2020-06-09 15:47:16,044 - mmdet - INFO - Epoch [5][5700/8856]	lr: 0.00010, eta: 1 day, 22:35:25, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5192, loss: 1.5192
2020-06-09 15:53:27,347 - mmdet - INFO - Epoch [5][6000/8856]	lr: 0.00010, eta: 1 day, 22:29:45, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.5100, loss: 1.5100
2020-06-09 15:59:38,636 - mmdet - INFO - Epoch [5][6300/8856]	lr: 0.00010, eta: 1 day, 22:24:01, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.4961, loss: 1.4961
2020-06-09 16:05:49,630 - mmdet - INFO - Epoch [5][6600/8856]	lr: 0.00010, eta: 1 day, 22:18:09, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.4969, loss: 1.4969
2020-06-09 16:12:00,015 - mmdet - INFO - Epoch [5][6900/8856]	lr: 0.00010, eta: 1 day, 22:12:03, time: 1.235, data_time: 0.038, memory: 4018, train_loss: 1.4868, loss: 1.4868
2020-06-09 16:18:10,088 - mmdet - INFO - Epoch [5][7200/8856]	lr: 0.00010, eta: 1 day, 22:05:51, time: 1.234, data_time: 0.039, memory: 4018, train_loss: 1.5101, loss: 1.5101
2020-06-09 16:24:20,527 - mmdet - INFO - Epoch [5][7500/8856]	lr: 0.00010, eta: 1 day, 21:59:46, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4859, loss: 1.4859
2020-06-09 16:30:31,238 - mmdet - INFO - Epoch [5][7800/8856]	lr: 0.00010, eta: 1 day, 21:53:45, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.4735, loss: 1.4735
2020-06-09 16:36:41,775 - mmdet - INFO - Epoch [5][8100/8856]	lr: 0.00010, eta: 1 day, 21:47:40, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4964, loss: 1.4964
2020-06-09 16:42:52,804 - mmdet - INFO - Epoch [5][8400/8856]	lr: 0.00010, eta: 1 day, 21:41:43, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.4963, loss: 1.4963
2020-06-09 16:49:03,421 - mmdet - INFO - Epoch [5][8700/8856]	lr: 0.00010, eta: 1 day, 21:35:39, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4958, loss: 1.4958
Traceback (most recent call last):
  File "F:/pytorch_room/mmdetection-master/main/Captions/mm_train.py", line 167, in <module>
    main()
  File "F:/pytorch_room/mmdetection-master/main/Captions/mm_train.py", line 163, in main
    meta=meta)
  File "F:\pytorch_room\mmdetection-master\mmdet\apis\caption_train.py", line 44, in train_caption_generator
    meta=meta)
  File "F:\pytorch_room\mmdetection-master\mmdet\apis\caption_train.py", line 169, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "D:\Anaconda3\envs\python36\lib\site-packages\mmcv\runner\runner.py", line 375, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\Anaconda3\envs\python36\lib\site-packages\mmcv\runner\runner.py", line 274, in train
    for i, data_batch in enumerate(data_loader): #epoches
  File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "D:\Anaconda3\envs\python36\lib\multiprocessing\queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "D:\Anaconda3\envs\python36\lib\site-packages\torch\multiprocessing\reductions.py", line 300, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't open shared event: <torch_14080_1261408088_event>, error code: <2

**Comment by Kristin-cantonese** [comment]
> Hi,did you solve it?, i got the same error during training
> 2020-06-09 13:50:06,087 - mmdet - INFO - workflow: [('train', 1)], max: 20 epochs
> 2020-06-09 13:56:22,778 - mmdet - INFO - Epoch [5][300/8856] lr: 0.00010, eta: 2 days, 1:18:43, time: 1.256, data_time: 0.092, memory: 4018, train_loss: 1.5078, loss: 1.5078
> 2020-06-09 14:02:24,076 - mmdet - INFO - Epoch [5][600/8856] lr: 0.00010, eta: 2 days, 0:12:16, time: 1.204, data_time: 0.037, memory: 4018, train_loss: 1.4931, loss: 1.4931
> 2020-06-09 14:08:27,846 - mmdet - INFO - Epoch [5][900/8856] lr: 0.00010, eta: 1 day, 23:52:32, time: 1.213, data_time: 0.037, memory: 4018, train_loss: 1.4962, loss: 1.4962
> 2020-06-09 14:14:34,010 - mmdet - INFO - Epoch [5][1200/8856] lr: 0.00010, eta: 1 day, 23:44:19, time: 1.221, data_time: 0.038, memory: 4018, train_loss: 1.4673, loss: 1.4673
> 2020-06-09 14:20:42,269 - mmdet - INFO - Epoch [5][1500/8856] lr: 0.00010, eta: 1 day, 23:40:12, time: 1.228, data_time: 0.038, memory: 4018, train_loss: 1.5070, loss: 1.5070
> 2020-06-09 14:26:49,468 - mmdet - INFO - Epoch [5][1800/8856] lr: 0.00010, eta: 1 day, 23:34:03, time: 1.224, data_time: 0.039, memory: 4018, train_loss: 1.5125, loss: 1.5125
> 2020-06-09 14:33:01,129 - mmdet - INFO - Epoch [5][2100/8856] lr: 0.00010, eta: 1 day, 23:32:50, time: 1.239, data_time: 0.039, memory: 4018, train_loss: 1.4812, loss: 1.4812
> 2020-06-09 14:39:12,045 - mmdet - INFO - Epoch [5][2400/8856] lr: 0.00010, eta: 1 day, 23:29:40, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5110, loss: 1.5110
> 2020-06-09 14:45:22,810 - mmdet - INFO - Epoch [5][2700/8856] lr: 0.00010, eta: 1 day, 23:25:42, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5186, loss: 1.5186
> 2020-06-09 14:51:34,151 - mmdet - INFO - Epoch [5][3000/8856] lr: 0.00010, eta: 1 day, 23:21:43, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.4890, loss: 1.4890
> 2020-06-09 14:57:46,231 - mmdet - INFO - Epoch [5][3300/8856] lr: 0.00010, eta: 1 day, 23:17:52, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4969, loss: 1.4969
> 2020-06-09 15:03:58,149 - mmdet - INFO - Epoch [5][3600/8856] lr: 0.00010, eta: 1 day, 23:13:31, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4965, loss: 1.4965
> 2020-06-09 15:10:10,007 - mmdet - INFO - Epoch [5][3900/8856] lr: 0.00010, eta: 1 day, 23:08:51, time: 1.240, data_time: 0.039, memory: 4018, train_loss: 1.4974, loss: 1.4974
> 2020-06-09 15:16:21,421 - mmdet - INFO - Epoch [5][4200/8856] lr: 0.00010, eta: 1 day, 23:03:43, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.5027, loss: 1.5027
> 2020-06-09 15:22:32,469 - mmdet - INFO - Epoch [5][4500/8856] lr: 0.00010, eta: 1 day, 22:58:16, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.5043, loss: 1.5043
> 2020-06-09 15:28:43,404 - mmdet - INFO - Epoch [5][4800/8856] lr: 0.00010, eta: 1 day, 22:52:39, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.4917, loss: 1.4917
> 2020-06-09 15:34:55,108 - mmdet - INFO - Epoch [5][5100/8856] lr: 0.00010, eta: 1 day, 22:47:20, time: 1.239, data_time: 0.039, memory: 4018, train_loss: 1.4882, loss: 1.4882
> 2020-06-09 15:41:05,177 - mmdet - INFO - Epoch [5][5400/8856] lr: 0.00010, eta: 1 day, 22:41:13, time: 1.234, data_time: 0.039, memory: 4018, train_loss: 1.5127, loss: 1.5127
> 2020-06-09 15:47:16,044 - mmdet - INFO - Epoch [5][5700/8856] lr: 0.00010, eta: 1 day, 22:35:25, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.5192, loss: 1.5192
> 2020-06-09 15:53:27,347 - mmdet - INFO - Epoch [5][6000/8856] lr: 0.00010, eta: 1 day, 22:29:45, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.5100, loss: 1.5100
> 2020-06-09 15:59:38,636 - mmdet - INFO - Epoch [5][6300/8856] lr: 0.00010, eta: 1 day, 22:24:01, time: 1.238, data_time: 0.039, memory: 4018, train_loss: 1.4961, loss: 1.4961
> 2020-06-09 16:05:49,630 - mmdet - INFO - Epoch [5][6600/8856] lr: 0.00010, eta: 1 day, 22:18:09, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.4969, loss: 1.4969
> 2020-06-09 16:12:00,015 - mmdet - INFO - Epoch [5][6900/8856] lr: 0.00010, eta: 1 day, 22:12:03, time: 1.235, data_time: 0.038, memory: 4018, train_loss: 1.4868, loss: 1.4868
> 2020-06-09 16:18:10,088 - mmdet - INFO - Epoch [5][7200/8856] lr: 0.00010, eta: 1 day, 22:05:51, time: 1.234, data_time: 0.039, memory: 4018, train_loss: 1.5101, loss: 1.5101
> 2020-06-09 16:24:20,527 - mmdet - INFO - Epoch [5][7500/8856] lr: 0.00010, eta: 1 day, 21:59:46, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4859, loss: 1.4859
> 2020-06-09 16:30:31,238 - mmdet - INFO - Epoch [5][7800/8856] lr: 0.00010, eta: 1 day, 21:53:45, time: 1.236, data_time: 0.039, memory: 4018, train_loss: 1.4735, loss: 1.4735
> 2020-06-09 16:36:41,775 - mmdet - INFO - Epoch [5][8100/8856] lr: 0.00010, eta: 1 day, 21:47:40, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4964, loss: 1.4964
> 2020-06-09 16:42:52,804 - mmdet - INFO - Epoch [5][8400/8856] lr: 0.00010, eta: 1 day, 21:41:43, time: 1.237, data_time: 0.039, memory: 4018, train_loss: 1.4963, loss: 1.4963
> 2020-06-09 16:49:03,421 - mmdet - INFO - Epoch [5][8700/8856] lr: 0.00010, eta: 1 day, 21:35:39, time: 1.235, data_time: 0.039, memory: 4018, train_loss: 1.4958, loss: 1.4958
> Traceback (most recent call last):
> File "F:/pytorch_room/mmdetection-master/main/Captions/mm_train.py", line 167, in
> main()
> File "F:/pytorch_room/mmdetection-master/main/Captions/mm_train.py", line 163, in main
> meta=meta)
> File "F:\pytorch_room\mmdetection-master\mmdet\apis\caption_train.py", line 44, in train_caption_generator
> meta=meta)
> File "F:\pytorch_room\mmdetection-master\mmdet\apis\caption_train.py", line 169, in _non_dist_train
> runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
> File "D:\Anaconda3\envs\python36\lib\site-packages\mmcv\runner\runner.py", line 375, in run
> epoch_runner(data_loaders[i], **kwargs)
> File "D:\Anaconda3\envs\python36\lib\site-packages\mmcv\runner\runner.py", line 274, in train
> for i, data_batch in enumerate(data_loader): #epoches
> File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 804, in **next**
> idx, data = self._get_data()
> File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 771, in _get_data
> success, data = self._try_get_data()
> File "D:\Anaconda3\envs\python36\lib\site-packages\torch\utils\data\dataloader.py", line 724, in _try_get_data
> data = self.data_queue.get(timeout=timeout)
> File "D:\Anaconda3\envs\python36\lib\multiprocessing\queues.py", line 113, in get
> return _ForkingPickler.loads(res)
> File "D:\Anaconda3\envs\python36\lib\site-packages\torch\multiprocessing\reductions.py", line 300, in rebuild_storage_filename
> storage = cls._new_shared_filename(manager, handle, size)
> RuntimeError: Couldn't open shared event: <torch_14080_1261408088_event>, error code: <2

I set the opt_val.num_threads=0 of function get_val_test_opts in train.py.
Hope to help you.

**Comment by y78h11b09** [comment]
Thank you very much, i try it

**Comment by y78h11b09** [comment]
There hasn't any error in the previous 4th  epoches training,  however error happened in the 5th. 
Do you tell me  anything about it?

**Comment by HuahongZhang** [comment]
Hi, I din't get such problem before so I am not sure why. Are you able to run the sample dataset (ISBI 2015)? If not, maybe you can try to run it firstly. If the sample dataset does not work, try a clean conda environment with pytorch version ~1.1.0?

**Comment by y78h11b09** [comment]
Thanks , i work at image-caption, not run the sample dataset(ISBI 2015), i solved it by upgrading the GPU-1080 ti driver. 



y78h11b09@163.com
 
From: HuahongZhang
Date: 2020-06-10 03:19
To: MedICL-VU/LesionSeg
CC: y78h11b09; Comment
Subject: Re: [MedICL-VU/LesionSeg] RuntimeError: Couldn't open shared event (#7)
Hi, I din't get such problem before so I am not sure why. Are you able to run the sample dataset (ISBI 2015)? If not, maybe you can try to run it firstly. If the sample dataset does not work, try a clean conda environment with pytorch version ~1.1.0?

**Comment by Kristin-cantonese** [comment]
> Hi, I din't get such problem before so I am not sure why. Are you able to run the sample dataset (ISBI 2015)? If not, maybe you can try to run it firstly. If the sample dataset does not work, try a clean conda environment with pytorch version ~1.1.0?

How do you preprocess with your in-house dataset? normalize with mean and std?? N4BiasFieldCorrection??

**Comment by HuahongZhang** [comment]
Sorry for the late reply, I am quite busy these days. It is described in our paper, we used N4ITK and normalized with KDE. However, I believe the normalization method does not affect the results too much

**Comment by arthursw** [comment]
I solved the error `RuntimeError: Couldn't open shared event: <torch_14080_1261408088_event>, error code:` by setting `opt_val.num_threads = 0` in `train.py` line 33, and I added `opt_val.num_threads = 0` line 58.
